name: Publish

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    - develop
    paths:
      - 'src/*'
      - 'tests/*'
      - 'Directory.Packages.props'
      - '.github/workflows/main.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      Authentication__OpenId__Authority: ${{ secrets.AUTHENTICATION__OPENID__AUTHORITY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./Training.JobVacancy.Backend.slnx

      - name: Build
        run: dotnet build ./Training.JobVacancy.Backend.slnx --configuration Release --no-restore

      - name: Lint OpenAPI Spec
        run: spectral lint src/Training.JobVacancy.Web.Server/OpenApi/Training.JobVacancy.Web.Server.json --ruleset src/Training.JobVacancy.Web.Server/OpenApi/.spectral.yaml

      - name: Test
        run: dotnet test ./Training.JobVacancy.Backend.slnx --configuration Release --no-build

      - name: Publish
        run: dotnet publish ./Training.JobVacancy.Backend.slnx --configuration Release --no-build

